### ISSUE TITLE
enhancement to cleanSbcAddresses

### ISSUE THREAD

**Issue by davehorton** [jambonz/db-helpers#13]
When this feature is installed, the existing rows in the table will have NULL for last_updated.  The sql statement:

https://github.com/jambonz/db-helpers/blob/61795220dd9967fe33ebd7d60ea8a80c8b688786/lib/clean-sbc-addresses.js#L13

should clean BOTH rows which have a NULL last_updated as well as those that have a last_updated value older than the interval

**Comment by xquanluu** [comment]
PR is merged
