### ISSUE TITLE
save tls_port and wss_port in sbc_addresses

### ISSUE THREAD

**Issue by davehorton** [jambonz/db-helpers#16]
As of release 0.8.3 the sbc_addresses table also includes optional columns for tls_port and wss_port, in addition to the 'port' column which has always kept the udp port.  The api should be updated to allow these new columns to be populated as well.  This will be optional as not every system will necessarily be listening for tls and wss.

**Comment by davehorton** [comment]
@xquanluu can this be closed?

**Comment by xquanluu** [comment]
Yes, PR merged and it's working in new released. closing this ticket
