### ISSUE TITLE
support mysql configuration with write master and read slaves

### ISSUE THREAD

**Issue by davehorton** [jambonz/db-helpers#21]
Currently both read and write transactions are written to the single database specified by the `JAMBONES_MYSQL_XXX` environment variables.  I would like to add an additional set of env vars:
```
JAMBONES_MYSQL_WRITE_HOST
JAMBONES_MYSQL_WRITE_PORT
JAMBONES_MYSQL_WRITE_USER
JAMBONES_MYSQL_WRITE_PASSWORD
JAMBONES_MYSQL_WRITE_DATABASE
JAMBONES_MYSQL_WRITE_CONNECTION_LIMIT
``` 
These are optional and if not provided then the behavior is as current.  However, for an installation that wishes to send all write transactions (e.g. INSERT, UPDATE, or DELETE) to a centralized master database, but read against a local readonly slave, they would provide values for the `JAMBONES_MYSQL_WRITE_XXX` env vars **in addition to** the `JAMBONES_MYSQL_XXX` which are still required.

**Comment by xquanluu** [comment]
start working on this.

**Comment by xquanluu** [comment]
[PR merged ](https://github.com/jambonz/db-helpers/pull/22/files)
Closing this issue
